'use client'
import { useMemo, useState } from 'react'
import { ArrowRight, CalendarDays, Check, Clock3, Sparkles } from 'lucide-react'
import { GuestShell } from '@/components/GuestShell'

export default function PlanPage(){
 const today=new Date().toISOString().slice(0,10)
 const [experience,setExperience]=useState('Fantasy Park + Snow Park'); const [group,setGroup]=useState('Family'); const [duration,setDuration]=useState('Full day'); const [date,setDate]=useState(today); const [generated,setGenerated]=useState(false)
 const slots=useMemo(()=>experience.includes('Snow') ? [['10:30','Arrival & entry'],['11:00','Fantasy Park family rides'],['12:45','Lunch & rest'],['14:00','Water activities'],['15:45','Snow Park'],['17:15','Wrap-up & exit']] : [['10:30','Arrival & entry'],['11:00','Family rides'],['12:30','Lunch & rest'],['13:30','Water activities'],['15:30','Adventure window'],['17:00','Wrap-up & exit']], [experience])
 return <GuestShell><main className="page"><div className="container"><div className="pageTitle"><div className="kicker">PLAN MY VISIT</div><h1>Build your day before you arrive.</h1><p>Start with the experiences you want, choose your group and pace, then review a practical visit plan before booking.</p></div><div className="plannerGrid"><section className="card formCard"><label>Experience<select value={experience} onChange={e=>{setExperience(e.target.value);setGenerated(false)}}><option>Fantasy Park + Snow Park</option><option>Fantasy Park</option><option>Snow Park</option><option>UpDown + Selfie Factory</option></select></label><label>Visit date<div className="inputLike"><CalendarDays size={16}/><input type="date" value={date} min={today} onChange={e=>setDate(e.target.value)} aria-label="Visit date"/></div></label><label>Group<select value={group} onChange={e=>setGroup(e.target.value)}><option>Family</option><option>Friends</option><option>School / Student</option><option>Corporate</option></select></label><label>Duration<select value={duration} onChange={e=>setDuration(e.target.value)}><option>Full day</option><option>Half day</option><option>3–4 hours</option></select></label><label>Interests</label><div className="chips"><span className="chip active">Water rides</span><span className="chip active">Family</span><span className="chip">Food</span><span className="chip">Adventure</span></div><button className="primary fullButton" onClick={()=>setGenerated(true)}><Sparkles size={16}/>{generated?'Plan refreshed':'Generate my plan'} <ArrowRight size={15}/></button></section><section className="card itinerary"><div className="itineraryHeader"><div><div className="kicker">SUGGESTED ITINERARY</div><h2>{group} · {duration}</h2><p className="muted">{new Date(`${date}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</p></div>{generated&&<span className="generated"><Check size={13}/> Ready</span>}</div>{slots.map(([time,title],i)=><div className="timeline" key={time}><span>{time}</span><i className={i===3?'hot':''}/><div><b>{title}</b><p><Clock3 size={12}/> Suggested window · confirm availability at booking</p></div></div>)}</section></div></div></main></GuestShell>
}
